ALTER TABLE RELR_KIT_LOCUS DROP FOREIGN KEY FK_ALLELE;
ALTER TABLE RELR_KIT_LOCUS DROP FOREIGN KEY FK_KIT;
ALTER TABLE RELR_KIT_LOCUS DROP FOREIGN KEY FK_LOCUS;

DROP TABLE RELR_KIT_LOCUS;
DROP TABLE RELT_ALLELE;
DROP TABLE RELT_KIT;
DROP TABLE RELT_LOCUS;