CREATE TABLE RELT_KIT (
  ID   INT         NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  CONSTRAINT RELT_KIT_PK PRIMARY KEY (ID)
);

CREATE TABLE RELT_LOCATION (
  ID   INT         NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  CONSTRAINT RELT_LOCATION_PK PRIMARY KEY (ID)
);

CREATE TABLE RELT_ALLELE (
  ID   INT         NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  CONSTRAINT RELT_ALLELE_PK PRIMARY KEY (ID)
);

CREATE TABLE RELT_LOCUS (
  ID    INT            NOT NULL AUTO_INCREMENT,
  VALUE DECIMAL(10, 5) NOT NULL,
  CONSTRAINT RELT_LOCUS_PK PRIMARY KEY (ID)
);

CREATE TABLE RELR_KIT_ALLELE (
  ID        INT NOT NULL AUTO_INCREMENT,
  KIT_ID    INT NOT NULL,
  ALLELE_ID INT NOT NULL,
  CONSTRAINT RELR_KIT_ALLELE_PK PRIMARY KEY (ID)
);

CREATE TABLE RELR_LOCA_ALLE_LOCUS (
  ID          INT            NOT NULL AUTO_INCREMENT,
  LOCATION_ID INT            NOT NULL,
  ALLELE_ID   INT            NOT NULL,
  LOCUS_ID    INT            NOT NULL,
  VALUE       DECIMAL(10, 7) NOT NULL,
  CONSTRAINT RELR_LOCA_ALLE_LOCUS_PK PRIMARY KEY (ID)
);

ALTER TABLE RELR_KIT_ALLELE ADD CONSTRAINT KA_FK_ALLELE FOREIGN KEY KA_FK_ALLELE (ALLELE_ID)
REFERENCES RELT_ALLELE (ID);

ALTER TABLE RELR_KIT_ALLELE ADD CONSTRAINT KA_FK_KIT FOREIGN KEY KA_FK_KIT (KIT_ID)
REFERENCES RELT_KIT (ID);

ALTER TABLE RELR_LOCA_ALLE_LOCUS ADD CONSTRAINT LAL_FK_ALLELE FOREIGN KEY LAL_FK_ALLELE (ALLELE_ID)
REFERENCES RELT_ALLELE (ID);

ALTER TABLE RELR_LOCA_ALLE_LOCUS ADD CONSTRAINT LAL_FK_LOCATION FOREIGN KEY LAL_FK_LOCATION (LOCATION_ID)
REFERENCES RELT_LOCATION (ID);

ALTER TABLE RELR_LOCA_ALLE_LOCUS ADD CONSTRAINT LAL_FK_LOCUS FOREIGN KEY LAL_FK_LOCUS (LOCUS_ID)
REFERENCES RELT_LOCUS (ID);

