ALTER TABLE RELR_KIT_ALLELE DROP FOREIGN KEY KA_FK_ALLELE;
ALTER TABLE RELR_KIT_ALLELE DROP FOREIGN KEY KA_FK_KIT;
ALTER TABLE RELR_LOCA_ALLE_LOCUS DROP FOREIGN KEY LAL_FK_ALLELE;
ALTER TABLE RELR_LOCA_ALLE_LOCUS DROP FOREIGN KEY LAL_FK_LOCATION;
ALTER TABLE RELR_LOCA_ALLE_LOCUS DROP FOREIGN KEY LAL_FK_LOCUS;

DROP TABLE RELR_KIT_ALLELE;
DROP TABLE RELR_LOCA_ALLE_LOCUS;
DROP TABLE RELT_ALLELE;
DROP TABLE RELT_KIT;
DROP TABLE RELT_LOCATION;
DROP TABLE RELT_LOCUS;

