-- Created by Vertabelo (http://vertabelo.com)
-- Script type: drop
-- Scope: [tables, references, sequences, views, procedures]
-- Generated at Thu Mar 26 03:57:55 UTC 2015



-- foreign keys
ALTER TABLE RELT_CASE DROP FOREIGN KEY CASE_FK_USER;
ALTER TABLE RELR_KIT_LOCUS DROP FOREIGN KEY KA_FK_KIT;
ALTER TABLE RELR_KIT_LOCUS DROP FOREIGN KEY KA_FK_LOCUS;
ALTER TABLE RELT_ALLELE_PROBABILITY DROP FOREIGN KEY RLP_FK_LOCUS;
ALTER TABLE RELR_PARENTS DROP FOREIGN KEY RP_FK_CASE;
ALTER TABLE RELR_SINGLE_PARENT DROP FOREIGN KEY RSP_FK_CASE;

-- tables
-- Table RELR_KIT_LOCUS
DROP TABLE RELR_KIT_LOCUS;
-- Table RELR_PARENTS
DROP TABLE RELR_PARENTS;
-- Table RELR_SINGLE_PARENT
DROP TABLE RELR_SINGLE_PARENT;
-- Table RELT_ALLELE_PROBABILITY
DROP TABLE RELT_ALLELE_PROBABILITY;
-- Table RELT_CASE
DROP TABLE RELT_CASE;
-- Table RELT_KIT
DROP TABLE RELT_KIT;
-- Table RELT_LOCATION
DROP TABLE RELT_LOCATION;
-- Table RELT_LOCUS
DROP TABLE RELT_LOCUS;
-- Table RELT_USER
DROP TABLE RELT_USER;



-- End of file.

