CREATE TABLE RELR_KIT_LOCUS (
  id       INT NOT NULL,
  locus_id INT NOT NULL,
  value    INT NOT NULL,
  kit_id   INT NOT NULL,
  CONSTRAINT RELR_KIT_LOCUS_pk PRIMARY KEY (id)
);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT PK_KIT
FOREIGN KEY (kit_id)
REFERENCES RELT_KIT (id);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT PK_LOCUS
FOREIGN KEY (locus_id)
REFERENCES RELT_LOCUS (id);