CREATE TABLE RELR_KIT_LOCUS (
  ID       INT NOT NULL AUTO_INCREMENT,
  LOCUS_ID INT NOT NULL,
  VALUE    INT NOT NULL,
  KIT_ID   INT NOT NULL,
  CONSTRAINT RELR_KIT_LOCUS_PK PRIMARY KEY (ID)
);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT PK_KIT
FOREIGN KEY (KIT_ID)
REFERENCES RELT_KIT (ID);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT PK_LOCUS
FOREIGN KEY (LOCUS_ID)
REFERENCES RELT_LOCUS (ID);