CREATE TABLE RELR_KIT_LOCUS (
  ID        INT          NOT NULL AUTO_INCREMENT,
  KIT_ID    INT          NOT NULL,
  ALLELE_ID INT          NOT NULL,
  LOCUS_ID  INT          NOT NULL,
  VALUE     DOUBLE(8, 6) NOT NULL,
  CONSTRAINT RELR_KIT_LOCUS_PK PRIMARY KEY (ID)
);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT FK_ALLELE
FOREIGN KEY (ALLELE_ID)
REFERENCES RELT_ALLELE (ID);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT FK_KIT
FOREIGN KEY (KIT_ID)
REFERENCES RELT_KIT (ID);

ALTER TABLE RELR_KIT_LOCUS ADD CONSTRAINT FK_LOCUS
FOREIGN KEY (KIT_ID)
REFERENCES RELT_LOCUS (ID);